Repository cap-js/cds-dbs, pull requests merged in 2024-07, with the labels that each got.

#717 chore: release main
  .release-please-manifest.json
  db-service/CHANGELOG.md
  db-service/package.json
  hana/CHANGELOG.md
  hana/package.json
Labels: autorelease: pending

#729 chore: release main
  .release-please-manifest.json
  db-service/CHANGELOG.md
  db-service/package.json
  hana/CHANGELOG.md
  hana/package.json
Labels: autorelease: pending

#590 feat(search): enable deep search with path expressions
  db-service/lib/SQLService.js
  db-service/lib/cqn4sql.js
  db-service/lib/infer/index.js
  db-service/lib/search.js
  db-service/test/bookshop/db/search.cds
  db-service/test/cqn4sql/search.test.js
  test/bookshop/db/data/sap.capire.bookshop-Authors.csv
  test/bookshop/db/schema.cds
  test/scenarios/bookshop/search.test.js
Labels: next release

#737 chore: release main
  .release-please-manifest.json
  postgres/CHANGELOG.md
  postgres/package.json
  sqlite/CHANGELOG.md
  sqlite/package.json
Labels: autorelease: pending

#758 deps: build script generates cds8 dependency in deployer app
  postgres/cds-plugin.js
Labels: postgres

#743 chore: release main
  .release-please-manifest.json
  db-service/CHANGELOG.md
  db-service/package.json
  hana/CHANGELOG.md
  hana/package.json
  postgres/CHANGELOG.md
  postgres/package.json
Labels: autorelease: pending
