Repository cap-js/cds-dbs, pull requests merged in 2024-05, with the labels that each got.

#615 fix(hana): Reference column alias in order by
  hana/lib/HANAService.js
Labels: next release

#567 fix: Improved placeholders and limit clause
  db-service/lib/cqn2sql.js
  db-service/test/cqn2sql/__snapshots__/delete.test.js.snap
  db-service/test/cqn2sql/__snapshots__/expression.test.js.snap
  db-service/test/cqn2sql/__snapshots__/function.test.js.snap
  db-service/test/cqn2sql/__snapshots__/select.test.js.snap
  db-service/test/cqn2sql/__snapshots__/update.test.js.snap
  db-service/test/cqn2sql/expression.test.js
  db-service/test/cqn2sql/select.test.js
  hana/lib/HANAService.js
  hana/lib/cql-functions.js
  hana/test/param-views.test.js
  postgres/lib/cql-functions.js
  sqlite/lib/SQLiteService.js
Labels: next release

#626 fix: improved `=` and `!=` with val `null` for HANA and Postgres
  db-service/lib/cqn2sql.js
  db-service/test/cqn2sql/expression.test.js
  hana/lib/HANAService.js
  test/scenarios/bookshop/read.test.js
Labels: next release

#587 chore: release main
  .release-please-manifest.json
  db-service/CHANGELOG.md
  db-service/package.json
  hana/CHANGELOG.md
  hana/package.json
  postgres/CHANGELOG.md
  postgres/package.json
  sqlite/CHANGELOG.md
  sqlite/package.json
Labels: autorelease: pending

#638 chore: release main
  .release-please-manifest.json
  db-service/CHANGELOG.md
  db-service/package.json
  hana/CHANGELOG.md
  hana/package.json
  sqlite/CHANGELOG.md
  sqlite/package.json
Labels: autorelease: pending

#657 chore: release main
  .release-please-manifest.json
  db-service/CHANGELOG.md
  db-service/package.json
Labels: autorelease: tagged

#658 chore: release main
  .release-please-manifest.json
  db-service/CHANGELOG.md
  db-service/package.json
  hana/CHANGELOG.md
  hana/package.json
  postgres/CHANGELOG.md
  postgres/package.json
Labels: autorelease: pending
