Repository cap-js/cds-dbs, pull requests merged in 2025-06, with the labels that each got.

#1224 fix: Allow raw streams to have empty results
  postgres/lib/PostgresService.js
Labels: next release

#1234 fix: Better opt in flag for builtin generic pool
  db-service/lib/common/generic-pool.js
  hana/lib/HANAService.js
Labels: bug

#1236 chore: release main
  .release-please-manifest.json
  db-service/CHANGELOG.md
  db-service/package.json
  hana/CHANGELOG.md
  hana/package.json
Labels: autorelease: pending
